---
title: "Case Study 01 - Beers"
author: "Randall Hendrickson"
date: "October 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Case Study 01

Beers

```{r beer_data}

library(RCurl)
library(data.table)
library(dplyr)
library(ggplot2)

github_file_1 <- "https://raw.githubusercontent.com/rhendrickson42/msds6306Case/master/data/Breweries.csv"
github_file_2 <- "https://raw.githubusercontent.com/rhendrickson42/msds6306Case/master/data/Beers.csv"

breweries <- read.csv(text = getURL(github_file_1), header = TRUE, sep = ",")
beers <- read.csv(text = getURL(github_file_2), header = TRUE, sep = ",")

# tidy the data
# 
# TODO - remove strange characters seen in dataframe, whitespace, view data, verify #001 Golden Amber Lager beer name
# from str(beer_world), also " AL", " AR", etc.

colnames(breweries)[1] <- "Brewery_id"
breweries$Name <- trimws(breweries$Name)
breweries$State <- trimws(breweries$State)

# TODO get Renvironment

```

## Question 1

```{r questions}

mydt <- setDT(breweries)[, .(count = uniqueN(Brewery_id)), by = State]
setorder(mydt, State)
mydt

# use dplyr
mydt2 <- breweries
mydt2 %>% group_by(State) %>% summarize(count=n()) %>% print(n = 100)

```
```{r question2}

# merge beer data and brewery data

beer_world <- merge(beers, breweries, by = "Brewery_id")
names(beer_world)[names(beer_world) == "Name.x"] <- "Beer_Name"
names(beer_world)[names(beer_world) == "Name.y"] <- "Brewery_Name"

# print first 6 observations
head(beer_world, 6)
# print last 6 observations
tail(beer_world, 6)

```

```{r question3}

# report number of NAs

num_NAs <- sapply(beer_world, function(x) sum(is.na(x)))
num_NAs

```

```{r question_4_5_6}
#4 compute the median alcohol content and IBU for each state Plot a bar chart to compare

state_ABV <- aggregate(beer_world["ABV"], by=beer_world[c("State")], FUN=median, na.rm=TRUE)
barplot(state_ABV$ABV, main="Beer ABV by State", names.arg = state_ABV$State)

state_IBU <- aggregate(beer_world["IBU"], by=beer_world[c("State")], FUN=median, na.rm=TRUE)
barplot(state_IBU$IBU, main="Beer IBU by State", names.arg = state_IBU$State)

#5 which state has the maximum alcoholic (ABV) beer?
state_ABV[which.max(state_ABV$ABV),]

# which state has the most bitter (IBU) beer?
state_IBU[which.max(state_IBU$IBU),]

# summary statistics for ABV variable

summary(state_ABV)

``` 
```{r beer_plot}


ggplot(beer_world, aes(x = IBU, y = ABV)) + 
  geom_point(colour = 'red', size = 1, na.rm=TRUE) + 
  labs(title = "Relationship between Bitterness and Alcohol content", subtitle = "Is bitter better?") + 
  labs(caption = "(based on data from ...?? where's the data from ??)")
  geom_smooth(method=lm, formula = x ~ y, size = 1, na.rm=TRUE)

```



