---
title: "Case Study 01 - Analysis"
author: "Randall Hendrickson"
date: "October 9, 2017"
output: html_document
params:
  state: "TX"
---

```{r setup_analysis, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)


if(!require("here")) cat("please install here package # devtools::install_github(\"krlmlr/here\")")
library(knitr)
library(here)
dataSetup_script <- here("scripts", "dataSetup.R")
analysis_script <- here("scripts", "analysis.R")
createDataSets_file <- here("scripts", "createDataSets.R")
source(dataSetup_script)
source(analysis_script)
```

read chunk = dataSetup_script.R
```{r setup_analysis_dataSetup}
read_chunk(paste(dataSetup_script))
```

read chunk = analysis.R
```{r setup_analysis_by_state}
read_chunk(paste(analysis_script))
```


## Beer and Brewery Analysis

```{r, beer_analysis_and_graphs}

summary(script_beer_world)

```



### Breweries and IBU by state

```{r, beer_analysis_graphs}
library(ggplot2)

# State to watch
state_to_watch <- params$state
state_to_watch

p <- ggplot(script_beer_world, aes(x = IBU)) + geom_freqpoly(binwidth = 3, na.rm = TRUE) + facet_wrap(~State)
p


```

### Bitter beers

```{r, code=readLines(createDataSets_file)}

# not sure yet how to read/pass data
```



## Information

From the above plot, we see the state of:
```{r, discuss_state}
# State to watch
state_to_watch <- params$state
state_to_watch
```

Has some interesting data.
